### ISSUE TITLE
Movie info crawling incomplete

### ISSUE THREAD

**Issue by webfmowsi** [brevis-ng/crawl-nguontv#2]
We found this useful plugin to install on one of our WordPress sites. Last August it was still working then we encountered an issue. The movies and their information as well as thumbnails don't get crawled completely. I don't what's happening.
![Capture](https://user-images.githubusercontent.com/112364028/188105702-19f2e4b9-3560-4552-bf6a-9325f31d7812.PNG)

**Comment by brevis-ng** [comment]
Hi webf, I’m sorry about this problem, I took a close look at the plugin and found there is a problem with identifying the image extension. I pushed a new commit, you can use the new plugin, if you have any problem don't hesitate to let me know.

**Comment by webfmowsi** [comment]
It's okay now. Thank you so much!
